version: '3.9'
services:
  api:
    build: ./api
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_DB=oneball_db
      - POSTGRES_USER=oneball_user
      - POSTGRES_PASSWORD=oneball_pass
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
  nginx:
    image: nginx:1.25
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
  db:
    image: postgres:16
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: oneball_db
      POSTGRES_USER: oneball_user
      POSTGRES_PASSWORD: oneball_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  celery:
    build:
      context: ./api
    command: celery -A api worker --loglevel=info
    volumes:
      - ./api:/app
    working_dir: /app
    depends_on:
      - api
      - redis
volumes:
  postgres_data:
