# Generated by Django 5.2.5 on 2025-08-14 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Grades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="更新日時"
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="年度")),
                (
                    "average",
                    models.FloatField(default=None, null=True, verbose_name="打率"),
                ),
                (
                    "games",
                    models.IntegerField(default=None, null=True, verbose_name="試合"),
                ),
                (
                    "plate_appearances",
                    models.IntegerField(default=None, null=True, verbose_name="打席"),
                ),
                (
                    "at_bats",
                    models.IntegerField(default=None, null=True, verbose_name="打数"),
                ),
                (
                    "hits",
                    models.IntegerField(default=None, null=True, verbose_name="安打"),
                ),
                (
                    "doubles",
                    models.IntegerField(default=None, null=True, verbose_name="二塁打"),
                ),
                (
                    "triples",
                    models.IntegerField(default=None, null=True, verbose_name="三塁打"),
                ),
                (
                    "home_runs",
                    models.IntegerField(default=None, null=True, verbose_name="本塁打"),
                ),
                (
                    "total_bases",
                    models.IntegerField(default=None, null=True, verbose_name="塁打"),
                ),
                (
                    "runs_batted_in",
                    models.IntegerField(default=None, null=True, verbose_name="打点"),
                ),
                (
                    "runs",
                    models.IntegerField(default=None, null=True, verbose_name="得点"),
                ),
                (
                    "strikeouts",
                    models.IntegerField(default=None, null=True, verbose_name="三振"),
                ),
                (
                    "walks",
                    models.IntegerField(default=None, null=True, verbose_name="四球"),
                ),
                (
                    "hit_by_pitch",
                    models.IntegerField(default=None, null=True, verbose_name="死球"),
                ),
                (
                    "sacrifice_bunts",
                    models.IntegerField(default=None, null=True, verbose_name="犠打"),
                ),
                (
                    "sacrifice_flies",
                    models.IntegerField(default=None, null=True, verbose_name="犠飛"),
                ),
                (
                    "stolen_bases",
                    models.IntegerField(default=None, null=True, verbose_name="盗塁"),
                ),
                (
                    "caught_stealing",
                    models.IntegerField(default=None, null=True, verbose_name="盗塁死"),
                ),
                (
                    "double_plays",
                    models.IntegerField(default=None, null=True, verbose_name="併殺打"),
                ),
                (
                    "on_base_percentage",
                    models.FloatField(default=None, null=True, verbose_name="出塁率"),
                ),
                (
                    "slugging_percentage",
                    models.FloatField(default=None, null=True, verbose_name="長打率"),
                ),
                ("ops", models.FloatField(default=None, null=True, verbose_name="OPS")),
                (
                    "runners_in_scoring_position",
                    models.FloatField(default=None, null=True, verbose_name="得点圏"),
                ),
                (
                    "errors",
                    models.IntegerField(default=None, null=True, verbose_name="失策"),
                ),
                (
                    "era",
                    models.FloatField(default=None, null=True, verbose_name="防御率"),
                ),
                (
                    "appearances",
                    models.IntegerField(default=None, null=True, verbose_name="登板"),
                ),
                (
                    "starts",
                    models.IntegerField(default=None, null=True, verbose_name="先発"),
                ),
                (
                    "complete_games",
                    models.IntegerField(default=None, null=True, verbose_name="完投"),
                ),
                (
                    "shutouts",
                    models.IntegerField(default=None, null=True, verbose_name="完封"),
                ),
                (
                    "no_walks",
                    models.IntegerField(default=None, null=True, verbose_name="無四球"),
                ),
                (
                    "quality_starts",
                    models.IntegerField(default=None, null=True, verbose_name="QS"),
                ),
                (
                    "relief_finishes",
                    models.IntegerField(
                        default=None, null=True, verbose_name="交代完了"
                    ),
                ),
                (
                    "wins",
                    models.IntegerField(default=None, null=True, verbose_name="勝利"),
                ),
                (
                    "losses",
                    models.IntegerField(default=None, null=True, verbose_name="敗戦"),
                ),
                (
                    "holds",
                    models.IntegerField(
                        default=None, null=True, verbose_name="ホールド"
                    ),
                ),
                (
                    "hold_points",
                    models.IntegerField(default=None, null=True, verbose_name="HP"),
                ),
                (
                    "saves",
                    models.IntegerField(default=None, null=True, verbose_name="セーブ"),
                ),
                (
                    "win_percentage",
                    models.FloatField(default=None, null=True, verbose_name="勝率"),
                ),
                (
                    "innings_pitched",
                    models.FloatField(default=None, null=True, verbose_name="投球回"),
                ),
                (
                    "batters_faced",
                    models.IntegerField(default=None, null=True, verbose_name="打者"),
                ),
                (
                    "hits_allowed",
                    models.IntegerField(default=None, null=True, verbose_name="被安打"),
                ),
                (
                    "home_runs_allowed",
                    models.IntegerField(
                        default=None, null=True, verbose_name="被本塁打"
                    ),
                ),
                (
                    "strikeouts_pitched",
                    models.IntegerField(default=None, null=True, verbose_name="奪三振"),
                ),
                (
                    "strikeout_rate",
                    models.FloatField(default=None, null=True, verbose_name="奪三振率"),
                ),
                (
                    "walks_allowed",
                    models.IntegerField(default=None, null=True, verbose_name="与四球"),
                ),
                (
                    "hit_by_pitch_allowed",
                    models.IntegerField(default=None, null=True, verbose_name="与死球"),
                ),
                (
                    "wild_pitches",
                    models.IntegerField(default=None, null=True, verbose_name="暴投"),
                ),
                (
                    "balks",
                    models.IntegerField(default=None, null=True, verbose_name="ボーク"),
                ),
                (
                    "runs_allowed",
                    models.IntegerField(default=None, null=True, verbose_name="失点"),
                ),
                (
                    "earned_runs",
                    models.IntegerField(default=None, null=True, verbose_name="自責点"),
                ),
                (
                    "quality_start_percentage",
                    models.FloatField(default=None, null=True, verbose_name="QS率"),
                ),
                (
                    "batting_average_against",
                    models.FloatField(default=None, null=True, verbose_name="被打率"),
                ),
                (
                    "strikeout_to_walk_ratio",
                    models.FloatField(default=None, null=True, verbose_name="K/BB"),
                ),
                (
                    "whip",
                    models.FloatField(default=None, null=True, verbose_name="WHIP"),
                ),
            ],
            options={
                "verbose_name": "成績",
                "verbose_name_plural": "成績",
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no", models.CharField(max_length=3, verbose_name="背番号")),
                ("name", models.CharField(max_length=100, verbose_name="選手名")),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("P", "投手"),
                            ("C", "捕手"),
                            ("IF", "内野手"),
                            ("OF", "外野手"),
                        ],
                        max_length=50,
                        verbose_name="登録ポジション",
                    ),
                ),
                ("height", models.PositiveIntegerField(verbose_name="身長")),
                ("weight", models.PositiveIntegerField(verbose_name="体重")),
                ("birthday", models.DateField(verbose_name="生年月日")),
                (
                    "pitch",
                    models.CharField(
                        choices=[("R", "右投げ"), ("L", "左投げ")],
                        max_length=50,
                        verbose_name="投球",
                    ),
                ),
                (
                    "bat",
                    models.CharField(
                        choices=[("R", "右打ち"), ("L", "左打ち")],
                        max_length=50,
                        verbose_name="打席",
                    ),
                ),
                ("salary", models.PositiveIntegerField(default=0, verbose_name="年俸")),
            ],
            options={
                "verbose_name": "選手",
                "verbose_name_plural": "選手",
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="チーム名")),
                (
                    "short_name",
                    models.CharField(max_length=50, unique=True, verbose_name="短縮名"),
                ),
                (
                    "alphabet",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="アルファベット"
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=50, unique=True, verbose_name="キー"),
                ),
                (
                    "league",
                    models.CharField(
                        choices=[("C", "セ・リーグ"), ("P", "パ・リーグ")],
                        max_length=50,
                        verbose_name="リーグ",
                    ),
                ),
            ],
            options={
                "verbose_name": "チーム",
                "verbose_name_plural": "チーム",
            },
        ),
        migrations.CreateModel(
            name="WinLose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="更新日時"
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="年度")),
                ("wins", models.IntegerField(default=0, verbose_name="勝利")),
                ("losses", models.IntegerField(default=0, verbose_name="敗戦")),
                ("draws", models.IntegerField(default=0, verbose_name="引分")),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="v1.team",
                        verbose_name="チーム",
                    ),
                ),
            ],
            options={
                "verbose_name": "勝敗",
                "verbose_name_plural": "勝敗",
            },
        ),
        migrations.CreateModel(
            name="GradesHistory",
            fields=[
                (
                    "grades_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="v1.grades",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="日付")),
            ],
            options={
                "verbose_name": "成績履歴",
                "verbose_name_plural": "成績履歴",
            },
            bases=("v1.grades",),
        ),
        migrations.AddField(
            model_name="grades",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="v1.player",
                verbose_name="選手",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="v1.team",
                verbose_name="チーム",
            ),
        ),
        migrations.CreateModel(
            name="WinLoseHistory",
            fields=[
                (
                    "winlose_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="v1.winlose",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="日付")),
            ],
            options={
                "verbose_name": "勝敗履歴",
                "verbose_name_plural": "勝敗履歴",
                "ordering": ["-year", "team__name"],
            },
            bases=("v1.winlose",),
        ),
    ]
